KS-21-1 extension функция подсчета гласных
lastbaks/KotlinSprintStart pull request #101
Opened 2024-07-30 16:14 UTC by lastbaks

2024-07-31 07:11 UTC, ievetrovdev requested changes

2024-07-31 07:11 UTC, ievetrovdev commented on src/main/kotlin/lesson_21/lesson21_task1.kt
> +fun String.vowelCount(input: String) : Int {
input тут не нужен. Попробуй более короткий вариант с помощью return this.count { it in vowels }

this — это ключевое слово, которое ссылается на текущий объект, в контексте которого выполняется код. Через него можно обращаться к свойствам и методам этого объекта.

this в контексте экстеншн метода ссылается на строку (текущий объект String), для которого вызван метод vowelCount.

this.count { it in vowels } означает, что мы вызываем метод count у текущей строки (this), то есть у строки, для которой был вызван метод vowelCount.

2024-08-01 07:57 UTC, ievetrovdev requested changes
Хорошо, но лишний файл попал, поправь пожалуйста

2024-08-01 08:09 UTC, lastbaks commented
Убрал лишний файл.

2024-08-01 14:32 UTC, ievetrovdev approved these changes

2024-08-01 15:57 UTC, merged