KS-21-2 extension функция подсчета суммы четных чисел списка
lastbaks/KotlinSprintStart pull request #102
Opened 2024-07-30 21:14 UTC by lastbaks

2024-07-31 07:19 UTC, ievetrovdev requested changes

2024-07-31 07:19 UTC, ievetrovdev commented on src/main/kotlin/lesson_21/lesson21_task2.kt
> +    numbers.forEach {
Предлагаю уже максимально использовать инструменты языка и для поиска суммы использовать соответствующие экстеншены: для фильтрации и нахождения суммы.

2024-07-31 07:19 UTC, ievetrovdev commented on src/main/kotlin/lesson_21/lesson21_task2.kt
> +fun List<Int>.evenNumbersSum(numbers: List<Int>): Int {
Та же проблема что и в 21-1, параметр не нужен

2024-07-31 16:18 UTC, lastbaks commented on src/main/kotlin/lesson_21/lesson21_task2.kt
> +    numbers.forEach {
Да, к тому же в таком варианте можно вообще собрать все в одно выражение и возвращаемое значение сделать после символа =, и получается супер читаемо!

2024-08-01 07:59 UTC, ievetrovdev approved these changes

2024-08-01 08:10 UTC, merged