KS-21-3 extension функция проверки здоровья персонажа
lastbaks/KotlinSprintStart pull request #103
Opened 2024-07-30 21:27 UTC by lastbaks

2024-07-31 07:20 UTC, ievetrovdev requested changes

2024-07-31 07:20 UTC, ievetrovdev commented on src/main/kotlin/lesson_21/lesson21_task3.kt
> +    if (currentHealth == maxHealth){
If лишний, можно сразу возвращать результат сравнения currentHealth == maxHealth

2024-07-31 19:03 UTC, lastbaks commented on src/main/kotlin/lesson_21/lesson21_task3.kt
> +    if (currentHealth == maxHealth){
Действительно. Тут тоже можно функцию сократить вплоть до одной строчки.

2024-08-01 08:01 UTC, ievetrovdev approved these changes

2024-08-01 08:06 UTC, merged