KS-21-4 extension функция добавления текста в начало файла
lastbaks/KotlinSprintStart pull request #104
Opened 2024-07-31 05:30 UTC by lastbaks

Текст добавляется в нижнем регистре.

2024-07-31 07:22 UTC, ievetrovdev requested changes

2024-07-31 07:22 UTC, ievetrovdev commented on src/main/kotlin/lesson_21/lesson21_task4.kt
> +fun String.addTextToStartOfFile(fileName: String) {
Функция не к строке, а к самому файлу нужно, и в параметр передать уже новый текст

2024-08-01 04:41 UTC, lastbaks commented on src/main/kotlin/lesson_21/lesson21_task4.kt
> +fun String.addTextToStartOfFile(fileName: String) {
Ок, переделал. Теперь в параметр вызываемой функции передаем нужный к добавлению текст.

2024-08-01 08:02 UTC, ievetrovdev approved these changes

2024-08-01 08:10 UTC, merged