KS-21-5 - проверка максимального навыка
lastbaks/KotlinSprintStart pull request #107
Opened 2024-08-02 18:31 UTC by lastbaks

2024-08-03 05:25 UTC, ievetrovdev requested changes

2024-08-03 05:25 UTC, ievetrovdev commented on src/main/kotlin/lesson_21/lesson21_task5.kt
> +fun Player3.maxCategory() = skills.maxByOrNull { it.value }?.key
Решение рабочее, однако, не совсем по ТЗ. Требуется создать экстеншн, который расширяет именно класс Map.

2024-08-03 14:19 UTC, lastbaks commented on src/main/kotlin/lesson_21/lesson21_task5.kt
> +fun Player3.maxCategory() = skills.maxByOrNull { it.value }?.key
Тогда либо я не до конца понял задание, либо нужны пояснения.
Если решение рабочее, то вот ниже переделанный код, в котором класс называется Map.
Но меня смущает один момент. Я сделал класс не с названием Map, потому что в задании указано конкретно - "Создай extension функцию для интерфейса Map". Я полез в docs, там  нашел подтверждение, что собственно map является интерфейсом... https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-map/

2024-08-04 07:56 UTC, ievetrovdev requested changes

2024-08-04 07:56 UTC, ievetrovdev commented on src/main/kotlin/lesson_21/lesson21_task5.kt
> +    var skills: MutableMap<String, Int> = mutableMapOf(
Смотри есть функция map() для перечисляемых типов, есть класс Map хранящая список ключ - значение. Это все базовые реализации. В этом задании создавать свой класс не нужно.
В этой строке ты и создаешь объект класса Map. Вот ждя этого класса и нужно функцию написать
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-map/

2024-08-04 13:13 UTC, lastbaks commented on src/main/kotlin/lesson_21/lesson21_task5.kt
> +    var skills: MutableMap<String, Int> = mutableMapOf(
Все, я понял. Я пытался к классу Map сделать функцию, но проблема была в том, что я не дописывал объявление функции. Я писал Map.maxCategory, а нужно после Map было указать типы значений K и V, для которых мы создаем функцию.

2024-08-05 07:11 UTC, ievetrovdev approved these changes
Да, теперь все отлично

2024-08-06 03:54 UTC, merged