KS-22-5 - путеводитель по галактике
lastbaks/KotlinSprintStart pull request #110
Opened 2024-08-06 14:45 UTC by lastbaks

2024-08-07 06:59 UTC, ievetrovdev requested changes

2024-08-07 06:59 UTC, ievetrovdev commented on src/main/kotlin/lesson_22/lesson22_task5.kt
> +    val(name, description, date, distance) = place1
в задании было сказано про компонентные функции (component1, component2...)

2024-08-07 11:04 UTC, lastbaks commented on src/main/kotlin/lesson_22/lesson22_task5.kt
> +    val(name, description, date, distance) = place1
Да, а в чем ошибка? В строке 16 с помощью деструктуризации в одной строке создаются несколько переменных.
Можно написать в несколько строк, явно прописав обращение к каждой компоненте объекта: ниже добавил код, в котором представлен такой вариант. По моему это просто два варианта использования одного и того же.

2024-08-08 07:48 UTC, ievetrovdev approved these changes
Вот сейчас использование компонентов, а не деструктуризации

2024-08-08 08:09 UTC, merged