KS-3-5 Chess party parsing record from "server"
lastbaks/KotlinSprintStart pull request #14
Opened 2024-06-14 04:28 UTC by lastbaks

2024-06-14 19:02 UTC, ievetrovdev requested changes

2024-06-14 19:02 UTC, ievetrovdev commented on src/main/kotlin/lesson_3/lesson3_task5.kt
> +    val movingData: String = "D2-D4;0"
Давай лучше применим split, и сразу передадим все нужные разделители

2024-06-14 21:36 UTC, lastbaks commented on src/main/kotlin/lesson_3/lesson3_task5.kt
> +    val movingData: String = "D2-D4;0"
Хорошо, можно сделать и так, но в этом случае лучше не создавать дополнительно разные переменные и присваивать им значения как в задании, а взять сразу получившийся после применения split массив и распечатать его элементы. Готово.

2024-06-15 09:17 UTC, ievetrovdev approved these changes
Все верно!

2024-06-15 20:47 UTC, merged