KS-4-2 Check average type of cargo
lastbaks/KotlinSprintStart pull request #16
Opened 2024-06-14 10:57 UTC by lastbaks

2024-06-14 13:23 UTC, ievetrovdev requested changes

2024-06-14 13:23 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson4_task2.kt
> +                        and (cargoWeight <= 100)
Немного смущает битовый оператор and.
В целом это не ошибка, но стоит помнить, что `&&` работает более оптимизированно для наших целей: если слева от знака выражение возвращает false, то правую часть он не будет проверять. Иногда это может благоприятно отображаться на экономии ресурсов
хоть и согласно https://kotlinlang.org/docs/coding-conventions.html конвенции нет строгих правил переноса длинных условия, на моей практике я везде встречал так: сначала на строке остается && / || , а затем строка переносится

2024-06-14 14:37 UTC, lastbaks commented on src/main/kotlin/lesson_4/lesson4_task2.kt
> +                        and (cargoWeight <= 100)
Спасибо, я и не знал про разницу.

2024-06-15 06:27 UTC, ievetrovdev requested changes

2024-06-15 06:27 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson4_task2.kt
> +                        and (cargoVolume < 100)}"
тут and остался)
и перенос немного не так сделан
```
println(
    "Груз с ввесом $cargoWeight килограмм " +
            "и объемом $cargoVolume литров " +
            "соответствует категории 'Average': " +
            "${(cargoWeight > 30) &&
                (cargoWeight <= 100) &&
                (cargoVolume < 100)}"
)
```

2024-06-15 21:06 UTC, lastbaks commented on src/main/kotlin/lesson_4/lesson4_task2.kt
> +                        and (cargoVolume < 100)}"
Последний AND пропустил случайно, исправил. Про оставление оператора сравнения в конце строки перед переносом запомнил, спасибо.

2024-06-16 06:33 UTC, ievetrovdev approved these changes
да

, отлично

2024-06-16 09:24 UTC, merged