KS-4-3 check weather for growing legumes
lastbaks/KotlinSprintStart pull request #17
Opened 2024-06-14 14:58 UTC by lastbaks

2024-06-15 06:28 UTC, ievetrovdev requested changes

2024-06-15 06:28 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson4_task3.kt
> +    var sunnyWeather: Boolean = true
Лучше использовать более релевантное название. В данном случае для Boolean переменной, которая является своеобразным "флагом" состояния. И для них рекомендуемая конструкция такая: isSunny / isAwningOpen

2024-06-15 06:28 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson4_task3.kt
> +    val conditionsForLegumes: Boolean = (sunnyWeather && openTent && airHumidity == 20 && season != "зима" )
Согласно ТЗ, значения сравниваются с критериями благоприятных условий, их, кстати, стоит вынести в константы, так как они постоянные и не планируются изменяться после компиляции.

2024-06-16 05:16 UTC, lastbaks commented on src/main/kotlin/lesson_4/lesson4_task3.kt
> +    var sunnyWeather: Boolean = true
Наименования булевых перменных изменены.

2024-06-16 05:36 UTC, lastbaks commented on src/main/kotlin/lesson_4/lesson4_task3.kt
> +    val conditionsForLegumes: Boolean = (sunnyWeather && openTent && airHumidity == 20 && season != "зима" )
Готово

2024-06-16 13:10 UTC, ievetrovdev approved these changes

2024-06-16 19:50 UTC, merged