KS-2-5 Вычисление сложного процента
lastbaks/KotlinSprintStart pull request #24
Opened 2024-06-18 04:45 UTC by lastbaks

2024-06-18 14:44 UTC, ievetrovdev requested changes

2024-06-18 14:44 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task5.kt
> +    val sum = deposit * ((1 + 0.167).pow(20))
Согласно ТЗ процентная ставка равна 16,7. Соответственно этими вводными данными и следует инициализировать программу. Нам нужно думать о поддержании и расширении программы, чтобы в любой момент можно было поменять только исходное значение. И не производить дополнительных манипуляций в уме.

2024-06-18 15:31 UTC, lastbaks commented on src/main/kotlin/lesson_2/lesson2_task5.kt
> +    val sum = deposit * ((1 + 0.167).pow(20))
Согласен

2024-06-19 06:45 UTC, ievetrovdev approved these changes

2024-06-19 07:06 UTC, merged