KS-6-2 Таймер
lastbaks/KotlinSprintStart pull request #27
Opened 2024-06-24 19:44 UTC by lastbaks

2024-06-24 20:03 UTC, lastbaks commented
Перезалил второй урок, так как изначально сделал его сразу с показом оставшихся секунд, а это нужно было делать только в уроке №3.

2024-06-25 07:31 UTC, ievetrovdev requested changes

2024-06-25 07:31 UTC, ievetrovdev commented on src/main/kotlin/lesson_6/lesson6_task2.kt
> +    while (countOfSeconds > 0) {
По условию вроде не нужно делать цикл. Может можно обойтись одним вызовом sleep?)

2024-06-25 10:09 UTC, lastbaks commented on src/main/kotlin/lesson_6/lesson6_task2.kt
> +    while (countOfSeconds > 0) {
Можно и без цикла, ниже добавил вариант с только функцией sleep. А так - цикл был добавлен специально, т.к. задача относится к уроку по циклам while и do while, поэтому я предполагаю - что нужно стараться решать задачи, используя элементы практикуемой темы, чтобы нарабатывать беглость кода.

2024-06-26 06:42 UTC, ievetrovdev approved these changes

2024-06-26 06:57 UTC, merged