KS-1-3 creating variables with date/time of the Gagarin's space flight
lastbaks/KotlinSprintStart pull request #3
Opened 2024-06-11 19:43 UTC by lastbaks

2024-06-12 13:20 UTC, ievetrovdev requested changes
Я оставил комментарий для доработки. чтобы правильно залить изменения, надо:
 - переключиться в Идее на нужную ветку
 - внести изменения и сделать коммит в эту ветку (следить чтобы в стейдж не добавились лишние задачи, которые не относятся к данной задаче)
 - отправить ссылку в бот на этот же пулл реквест к соответствующей задаче

2024-06-12 13:20 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task3.kt
> +    //и вариант печати по предполагаемой подсказке из задания с использованием нескольких функций print()
первый вариант лучше)

2024-06-12 13:20 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task3.kt
> +    var hour: Int = 9
В целом результат есть! но в примере в ТЗ цифры начинаются с 0.
Вообще нормальная практика, если сервер присылает дату или время строкой.
Давай объявим строки и сделаем правильный формат)

2024-06-12 13:34 UTC, lastbaks commented on src/main/kotlin/lesson_1/lesson1_task3.kt
> +    //и вариант печати по предполагаемой подсказке из задания с использованием нескольких функций print()
оставляем первый вариант

2024-06-12 13:42 UTC, lastbaks commented on src/main/kotlin/lesson_1/lesson1_task3.kt
> +    var hour: Int = 9
Хорошо, сделаю так.

2024-06-13 07:30 UTC, ievetrovdev approved these changes

2024-06-13 19:02 UTC, merged