KS-6-5 Доработка модуля авторизации: решение математической задачи
lastbaks/KotlinSprintStart pull request #30
Opened 2024-06-25 04:40 UTC by lastbaks

2024-06-26 06:40 UTC, ievetrovdev requested changes

2024-06-26 06:40 UTC, ievetrovdev commented on src/main/kotlin/lesson_6/lesson6_task5.kt
> +                println("Доступ запрещен")
Этот вывод можно вынести за пределы цикла)

2024-06-26 07:29 UTC, lastbaks commented on src/main/kotlin/lesson_6/lesson6_task5.kt
> +                println("Доступ запрещен")
Да, можно. Тогда меняю оператор break на return, чтобы в случае верного ввода не печаталось "доступ запрещен"

2024-06-27 06:46 UTC, ievetrovdev approved these changes

2024-06-27 06:47 UTC, merged