KS-7-1 Генератор пароля из шести символов
lastbaks/KotlinSprintStart pull request #31
Opened 2024-06-25 16:51 UTC by lastbaks

Внутри кода два решения. В первом числа и символы в пароле чередуются случайным образом (просто входят в набор для генерации пароля), а во втором чередуются строго по очереди. Второй вариант сделать без использования списка у меня не вышло - если нужно именно без списка - прошу помощи, т.к. у меня получались громоздкие конструкции.

2024-06-26 07:27 UTC, ievetrovdev requested changes

2024-06-26 07:27 UTC, ievetrovdev commented on src/main/kotlin/lesson_7/lesson7_task1.kt
> +    val passwordOne = List(length) { charset.random() }.joinToString("")
Этот вариант не совсем верен, так как по ТЗ нужно именно чередование

2024-06-26 07:27 UTC, ievetrovdev commented on src/main/kotlin/lesson_7/lesson7_task1.kt
> +        randomInt = (1..9).random().toString()
В своем решении ты создаешь диапазон при каждой итерации цикла. Давай зададим переменные с диапазоном чисел и диапазоном строк, а в цикле будем их использовать.
В данной главе мы в первую очередь пробуем диапазоны, и списки использовать можно, но в данном случае не совсем оправдано. Можно passwordTwo сделать пустой строкой, и в нее добавлять по рандомном символу

2024-06-26 16:11 UTC, lastbaks commented on src/main/kotlin/lesson_7/lesson7_task1.kt
> +        randomInt = (1..9).random().toString()
Хорошо, готово.

2024-06-27 06:53 UTC, ievetrovdev approved these changes
Да, отлично

2024-06-27 07:43 UTC, merged