KS-7-5 генератор пароля с выбором длины от 6 символов
lastbaks/KotlinSprintStart pull request #35
Opened 2024-06-26 03:45 UTC by lastbaks

2024-06-26 16:09 UTC, ievetrovdev requested changes

2024-06-26 16:09 UTC, ievetrovdev commented on src/main/kotlin/lesson_7/lesson7_task5.kt
> +    password = List(length) { charset.random() }.joinToString("")
В данной реализации хоть ты и складываешь все три диапазона в один набор символов, но есть вероятность, что рандомайзер при генерации пароля упустит один или несколько типов символов. 
Стоит изменить подход. Например, сперва добавлять обязательные символы, затем рандомно оставшиеся из общего набора.

2024-06-26 17:00 UTC, lastbaks commented on src/main/kotlin/lesson_7/lesson7_task5.kt
> +    password = List(length) { charset.random() }.joinToString("")
Да, действительно - такая вероятность есть. Совет хороший - добавил вначале по одному символу каждого вида, а потом остаток длины строки из общего набора.

2024-06-27 06:58 UTC, ievetrovdev requested changes

2024-06-27 06:58 UTC, ievetrovdev commented on src/main/kotlin/lesson_7/lesson7_task5.kt
> +    val charset = ('A'..'Z') + ('a'..'z') + ('0'..'9')
Так то вроде все нормально, но есть моменты которые прям хочется улучшить. Тут же можно использовать уже созданные интервалы smallLetters bigLetters intValues.

2024-06-27 06:58 UTC, ievetrovdev commented on src/main/kotlin/lesson_7/lesson7_task5.kt
> +    password += List(length - 3) { charset.random() }.joinToString("")
такой алгоритм с первыми тремя обязательными символами можно раскрыть и облегчить взломщику работу. Стоит еще конечную строку с паролем перемешать. Сделать это можно, используя extension shuffle().
Но это уже чтоб прям идеально стало)

2024-06-27 10:07 UTC, lastbaks commented on src/main/kotlin/lesson_7/lesson7_task5.kt
> +    val charset = ('A'..'Z') + ('a'..'z') + ('0'..'9')
Да, действительно. И даже скобочки от диапазонов не нужны. Для меня все конструкции пока неочевидны и рефактор готового кода я воспринимаю пока так: - "О, наконец, получилось. Оставлю все так, чтобы не поломалось."

2024-06-27 18:24 UTC, lastbaks commented on src/main/kotlin/lesson_7/lesson7_task5.kt
> +    password += List(length - 3) { charset.random() }.joinToString("")
Ок, добавил. На мой взгляд получилось немного громоздко - сначала набиваем символами строку, потом переводим ее в список лишь для того, чтобы перемешать, но не громоздко у меня пока не получается. видимо либо придет с опытом, либо пойму - что это - норма))

2024-06-28 07:22 UTC, ievetrovdev approved these changes

2024-06-28 07:22 UTC, ievetrovdev commented on src/main/kotlin/lesson_7/lesson7_task5.kt
> +    for (char in randomString) {
+- все нормально, только как ты и сказал громоздко, можно было сразу все символы добавлять в password, и только в самом конце преобразовывать в строку

2024-06-28 07:35 UTC, merged