KS-9-3 подсчет количества ингредиентов на порции блюда
lastbaks/KotlinSprintStart pull request #43
Opened 2024-06-27 04:33 UTC by lastbaks

2024-06-27 15:15 UTC, ievetrovdev requested changes

2024-06-27 15:15 UTC, ievetrovdev commented on src/main/kotlin/lesson_9/lesson9_task3.kt
> +    println("Сливочное масло - ${countOfIngredients[2] * countOfPortions} грамм.")
Рабочий, но не универсальный вариант, если ингредиентов будет больше, надо будет переписывать прогу. Попробуй использовать map

2024-06-27 19:32 UTC, lastbaks commented on src/main/kotlin/lesson_9/lesson9_task3.kt
> +    println("Сливочное масло - ${countOfIngredients[2] * countOfPortions} грамм.")
Ок, сделал с map. Раньше про map ничего не знал, поэтому это для меня новый опыт.

2024-06-28 07:24 UTC, ievetrovdev requested changes

2024-06-28 07:24 UTC, ievetrovdev commented on src/main/kotlin/lesson_9/lesson9_task3.kt
> +    val ingredients: MutableMap<String, Int> =
Тут ты меня немного оне понял) я говорил про метод map у списка, а не класс map. Текущий вариант тоже рабочий, и хорошо что ты его выучил. Но давай более правильный вариант тоже выучим)

2024-07-01 13:16 UTC, ievetrovdev approved these changes
Отлично

2024-07-01 13:30 UTC, merged