KS-9-5 пять уникальных ингредиентов
lastbaks/KotlinSprintStart pull request #45
Opened 2024-06-28 04:34 UTC by lastbaks

Ссори, когда делал ветку - случайно назвал ее 9-6.

2024-06-28 07:29 UTC, ievetrovdev requested changes

2024-06-28 07:29 UTC, ievetrovdev commented on src/main/kotlin/lesson_9/lesson9_task5.kt
> +    val capitalizedString = uniqueIngredients.replaceFirstChar { if (it.isLowerCase()) it.titlecase(Locale.getDefault()) else it.toString() }
логика правильная использовать replaceFirst, но внутри можно опустить условие, и просто любую букву делать большой (и маленькую и большую). Так можно будет чуть упростить

2024-06-28 07:29 UTC, ievetrovdev commented on src/main/kotlin/lesson_9/lesson9_task5.kt
> +    val uniqueIngredients = (listOfIngredients.distinct()).joinToString(separator = ",")
Отличный и правильный вариант убрать дублирование. Но хочется чтобы и попробовал второй вариант, использовать коллекцию которая не умеет хранить повторы - Set. Давай для своего развитие ее попробуешь

2024-06-28 15:52 UTC, lastbaks commented on src/main/kotlin/lesson_9/lesson9_task5.kt
> +    val capitalizedString = uniqueIngredients.replaceFirstChar { if (it.isLowerCase()) it.titlecase(Locale.getDefault()) else it.toString() }
Логично)

2024-06-28 15:53 UTC, lastbaks commented on src/main/kotlin/lesson_9/lesson9_task5.kt
> +    val uniqueIngredients = (listOfIngredients.distinct()).joinToString(separator = ",")
С set оказалось интересно, мне понравилось!

2024-06-29 06:10 UTC, ievetrovdev approved these changes
Отлично)

2024-06-29 20:10 UTC, merged