KS-10-3 - генератор пароля
lastbaks/KotlinSprintStart pull request #48
Opened 2024-06-29 20:08 UTC by lastbaks

Генератор пароля заданной длины с чередованием цифр и спецсимволов.

2024-06-29 23:04 UTC, ievetrovdev requested changes

2024-06-29 23:04 UTC, ievetrovdev commented on src/main/kotlin/lesson_10/lesson10_task3.kt
> +    val randomLetter = listOf('!', '"', '#', '$', '%', '&', '\'', '(', ')', '*', '+', ',', '-', '.', '/')
По символам можно также итерироваться. Посмотри на вот эту табличку и попробуй найти закономерность) https://www.industrialnets.ru/files/misc/ascii.pdf

2024-06-30 05:42 UTC, lastbaks commented on src/main/kotlin/lesson_10/lesson10_task3.kt
> +    val randomLetter = listOf('!', '"', '#', '$', '%', '&', '\'', '(', ')', '*', '+', ',', '-', '.', '/')
Ну да, решение очевидно. Удобно.

2024-06-30 21:11 UTC, ievetrovdev approved these changes
Все верно!

2024-07-01 03:24 UTC, merged