KS-10-4 - игра в кости в возможностью повторов
lastbaks/KotlinSprintStart pull request #49
Opened 2024-06-29 20:57 UTC by lastbaks

2024-06-29 23:07 UTC, ievetrovdev requested changes

2024-06-29 23:07 UTC, ievetrovdev commented on src/main/kotlin/lesson_10/lesson10_task4.kt
> +var readyToGame = true
Обычно стараются избегать использования глобальных переменных, по крайней мере в таком виде. Перенеси их в методы.

2024-06-30 05:32 UTC, lastbaks commented on src/main/kotlin/lesson_10/lesson10_task4.kt
> +var readyToGame = true
Хорошо, сделал. А в каком виде их стоит использовать?

2024-06-30 21:07 UTC, ievetrovdev commented on src/main/kotlin/lesson_10/lesson10_task4.kt
> +var readyToGame = true
Ну в Котлине обычно всегда не стоит, да бывают там общие сервисы, там репозитории, которые предоставляют одну точку входа для работы с БД, или внешним сервисом, для всех методов одного класса. Реже бывают счетчики. Но в большинстве случаев, это обоснованно архитектурой проекта. Обычно такие переменные точно не могут быть изменены, либо они должны иметь возможность быть измененными из любой точки кода.

2024-06-30 21:09 UTC, ievetrovdev commented on src/main/kotlin/lesson_10/lesson10_task4.kt
> +var readyToGame = true
В общем, когда будут такие моменты, глобальность будет обоснована

2024-06-30 21:09 UTC, ievetrovdev approved these changes
Все верно!

2024-07-01 03:26 UTC, merged