KS-1-5 formatted print of variables
lastbaks/KotlinSprintStart pull request #5
Opened 2024-06-11 21:29 UTC by lastbaks

2024-06-12 13:22 UTC, ievetrovdev requested changes

2024-06-12 13:22 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    val hours: Int = totalSeconds / 3600
Чтобы снизить риск ошибок, предлагаю все “голые” числа вынести в константу. Кроме того это [магические числа](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что тоже не является хорошей практикой.

2024-06-12 13:22 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    val minutes: Int = totalSeconds / 60 - (hours * 60)
Подсчитано верно, но давай попробуй белее элегантный вариант используя только деление и остаток от деления (/ и %)

2024-06-12 13:22 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    println("$hoursString:$minutesString:$secondsString")
Отлично!) можно даже еще аккуратнее сделать
println("%02d:%02d:%02d".format(hours, minutes, seconds))

2024-06-13 12:46 UTC, ievetrovdev requested changes

2024-06-13 12:46 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +const val  TOTAL_SECONDS: Short = 6480
По поводу объявления констант: наша программа должна быть универсальной, поддерживать другие входные значения. Поэтому тут мы инициализируем значения из ТЗ в обычные переменные. Если их инициализировать через константы, то они после компиляции превратятся в обычные значения и их нельзя будет переиспользовать
Что значит 6480 не константа,а 60 и 3600 да

2024-06-13 15:49 UTC, lastbaks commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +const val  TOTAL_SECONDS: Short = 6480
Теперь стало понятно. Я не мог дать себе четкий критерий, по которому определять - стоит делать константу или можно обойтись переменной

2024-06-14 07:16 UTC, ievetrovdev approved these changes
Отлично, дальше по урокам будет опыт определения

2024-06-14 07:19 UTC, merged