KS-10-5 - авторизация и получение списка товаров
lastbaks/KotlinSprintStart pull request #50
Opened 2024-07-01 11:56 UTC by lastbaks

2024-07-01 20:19 UTC, ievetrovdev requested changes

2024-07-01 20:19 UTC, ievetrovdev commented on src/main/kotlin/lesson_10/lesson10_task5.kt
> +}
Слишком громоздкий метод, вынеси генерацию токена в отдельный

2024-07-01 20:19 UTC, ievetrovdev commented on src/main/kotlin/lesson_10/lesson10_task5.kt
> +        var randomChar = ('a' .. 'z').random()
Диапазоны можно объединить через +, и добавь большие буквы

2024-07-01 20:19 UTC, ievetrovdev commented on src/main/kotlin/lesson_10/lesson10_task5.kt
> +        }
Попробуй сделать через (1..32).map

2024-07-01 20:54 UTC, lastbaks commented on src/main/kotlin/lesson_10/lesson10_task5.kt
> +}
Все готово, но у меня есть по каждому пункту "оправдания" - Генерацию я сам хотел сделать отдельно, но в задании точно перечислены методы и метод верификации в себе должен содержать генерацию токена - поэтому он и вышел таким навороченным)

2024-07-01 20:57 UTC, lastbaks commented on src/main/kotlin/lesson_10/lesson10_task5.kt
> +        var randomChar = ('a' .. 'z').random()
Готово. вынес генерацию в отдельный метод и объединил диапазоны. при 32 элементах маловероятен факт, что какой то из символов не будет использован, поэтому ок)

2024-07-01 20:57 UTC, lastbaks commented on src/main/kotlin/lesson_10/lesson10_task5.kt
> +        }
готово)

2024-07-02 17:34 UTC, ievetrovdev approved these changes
Все верно, молодец!

2024-07-02 18:01 UTC, merged