KS-11-4 - сущности рецепта, категории, ингредиента
lastbaks/KotlinSprintStart pull request #54
Opened 2024-07-03 05:44 UTC by lastbaks

2024-07-03 07:15 UTC, ievetrovdev requested changes

2024-07-03 07:15 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task4.kt
> +class Category(
Категория должна содержать список рецептов. Тогда зависимость была бы такая: Ingredient -> Recipe (Dish) -> Category

2024-07-03 07:15 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task4.kt
> +    val countOfIngredient: MutableMap<MutableList<Ingredient>, Int>,
Для чего здесь список списков? Мы же можем получить количество ингредиентов просто используя `ingredients.size`

2024-07-03 07:15 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task4.kt
> +    val category: Category,
Это свойство также можно удалить

2024-07-03 17:28 UTC, lastbaks commented on src/main/kotlin/lesson_11/lesson11_task4.kt
> +    val countOfIngredient: MutableMap<MutableList<Ingredient>, Int>,
Проектирование классов- это уже посложнее, чем задачки по переменным или функциям, тут я "плаваю", поэтому тут мне потребуется пояснение. Список списков я сделал, т.к. на правом изображении дизайна из фигмы отображен рецепт, в котором в зависимости от количества порций сразу меняется количество необходимых ингредиентов. Если количество указать как свойство класса Ingredients, то при создании экземпляра продукта мы сразу присвоим ему количество и оно будет фиксировано для разных рецептов, а оно должно быть разным. Я нашел только такое решение. А ingredients.size нам даст количество элементов списка, а не количество каждого ингредиента для отображения. У меня пока плохо складывается представление, как правильно это сделать.

2024-07-03 20:23 UTC, lastbaks commented on src/main/kotlin/lesson_11/lesson11_task4.kt
> +class Category(
Ок, я изначально по другому понял идею - переделал.

2024-07-03 20:24 UTC, lastbaks commented on src/main/kotlin/lesson_11/lesson11_task4.kt
> +    val category: Category,
... И соответственно это свойство удалил - стало ненужным.

2024-07-03 20:26 UTC, lastbaks commented on src/main/kotlin/lesson_11/lesson11_task4.kt
> +    val countOfIngredient: MutableMap<MutableList<Ingredient>, Int>,
дополнение: - поправил "список списков" - это map, в котором записываются в ключ - Ингредиент, а в значение - его количество. Так мы реализуем возможность записывать объем каждого из ингредиентов в рецепте.

2024-07-04 09:25 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task4.kt
> +    val countOfIngredient: MutableMap<MutableList<Ingredient>, Int>,
Да, сейчас стало гораздо лучше) Молодец что разобрался!

2024-07-04 09:25 UTC, ievetrovdev approved these changes

2024-07-04 09:25 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task4.kt
> +class Dish(
Теперь все отлично)

2024-07-04 10:01 UTC, merged