KS-12-1 - Данные о погоде
lastbaks/KotlinSprintStart pull request #55
Opened 2024-07-04 18:28 UTC by lastbaks

2024-07-05 03:17 UTC, ievetrovdev approved these changes

2024-07-05 03:18 UTC, ievetrovdev requested changes

2024-07-05 03:18 UTC, ievetrovdev commented on src/main/kotlin/lesson_12/lesson12_task1.kt
> +    var precipitation: Boolean = false
Булеан переменные принято называть с is или has. Давай переименуем

2024-07-05 04:28 UTC, lastbaks commented on src/main/kotlin/lesson_12/lesson12_task1.kt
> +    var precipitation: Boolean = false
Да, забыл. Практика и еще раз практика)

2024-07-06 07:24 UTC, ievetrovdev approved these changes

2024-07-06 10:53 UTC, merged