KS-12-2 - Данные о погоде - версия без первичной инициализации
lastbaks/KotlinSprintStart pull request #56
Opened 2024-07-04 18:45 UTC by lastbaks

2024-07-05 03:19 UTC, ievetrovdev requested changes

2024-07-05 03:19 UTC, ievetrovdev commented on src/main/kotlin/lesson_12/lesson12_task2.kt
> +    var precipitation: Boolean
Все отлично, только давай переименуем как в прошлом ПРе)

2024-07-05 04:31 UTC, lastbaks commented on src/main/kotlin/lesson_12/lesson12_task2.kt
> +    var precipitation: Boolean
готово)

2024-07-06 07:25 UTC, ievetrovdev approved these changes

2024-07-06 10:54 UTC, merged