KS-12-3 - Данные о погоде - версия c градусами кельвина
lastbaks/KotlinSprintStart pull request #57
Opened 2024-07-04 19:07 UTC by lastbaks

Привет. У меня вопрос по применимости такого варианта объявления класса в реальных задачах - такая версия создания класса, как в этом примере -  где в первичном конструкторе мы перечисляем все свойства без инициализации, далее в теле класса их инициализируем произвольными значениями - имеет смысл? Мне кажется, что выделение памяти для них в первичном конструкторе ничем по сути не отличается.

2024-07-05 03:27 UTC, ievetrovdev commented
> Привет. У меня вопрос по применимости такого варианта объявления класса в реальных задачах - такая версия создания класса, как в этом примере - где в первичном конструкторе мы перечисляем все свойства без инициализации, далее в теле класса их инициализируем произвольными значениями - имеет смысл? Мне кажется, что выделение памяти для них в первичном конструкторе ничем по сути не отличается.

Привет. Этот вариант применим если мы не хотим давать возможность обращаться напрямую к начальным значениям (которые передали в конструктор), а хотим давать доступ только к рассчитанным свойствам. В данном задании мы хотим получать значения в Цельсиях, а не Кельвинах, поэтому входные данные нас не интересуют)

2024-07-05 03:28 UTC, ievetrovdev requested changes

2024-07-05 03:28 UTC, ievetrovdev commented on src/main/kotlin/lesson_12/lesson12_task3.kt
> +    var dayTemperature = _dayTemperature
Здесь должно быть преобразование в градусы Цельсия

2024-07-05 03:28 UTC, ievetrovdev commented on src/main/kotlin/lesson_12/lesson12_task3.kt
> +    _precipitation: Boolean
Стоит изменить название

2024-07-05 03:28 UTC, ievetrovdev commented on src/main/kotlin/lesson_12/lesson12_task3.kt
> +        println("Температура днем: ${dayTemperature - 273} градусов цельсия")
273 стоит вынести в переменную или константу

2024-07-05 04:55 UTC, lastbaks commented on src/main/kotlin/lesson_12/lesson12_task3.kt
> +    _precipitation: Boolean
Как и в предыдущих. ок)

2024-07-05 04:55 UTC, lastbaks commented on src/main/kotlin/lesson_12/lesson12_task3.kt
> +        println("Температура днем: ${dayTemperature - 273} градусов цельсия")
готово.

2024-07-06 07:25 UTC, ievetrovdev approved these changes

2024-07-06 10:54 UTC, merged