KS-12-4 - Данные о погоде - версия с блоком init
lastbaks/KotlinSprintStart pull request #58
Opened 2024-07-04 19:25 UTC by lastbaks

К этому уроку у меня тоже есть вопрос.
Когда я убрал из функции main вызов метода распечатки информации о погоде из класса - idea сообщила мне, что переменная объекта класса нигде не используется и предложила ее удалить. Я ради интереса согласился и оказалось, что так в этом случае тоже работает. Я понимаю, что это вероятно подходит лишь в таких примитивных случаях, когда после отработки init ничего не происходит, и в реальной продуктовой разработке мы будем дальше работать с объектами ... но как это работает? У нас вроде нет выделения памяти под объект, а действия над ним производятся и результат есть.

2024-07-05 03:33 UTC, ievetrovdev commented
> К этому уроку у меня тоже есть вопрос. Когда я убрал из функции main вызов метода распечатки информации о погоде из класса - idea сообщила мне, что переменная объекта класса нигде не используется и предложила ее удалить. Я ради интереса согласился и оказалось, что так в этом случае тоже работает. Я понимаю, что это вероятно подходит лишь в таких примитивных случаях, когда после отработки init ничего не происходит, и в реальной продуктовой разработке мы будем дальше работать с объектами ... но как это работает? У нас вроде нет выделения памяти под объект, а действия над ним производятся и результат есть.

В данном случае мы не работаем с объектом напрямую. Мы его создали, далее все операции внутри него происходят без нашего участия (при инициализации). Сам объект в любом случае занимает место в памяти, но мы не храним на него ссылку и соответственно не выделяется дополнительная память под эту переменную.

2024-07-05 03:34 UTC, ievetrovdev requested changes

2024-07-05 03:34 UTC, ievetrovdev commented on src/main/kotlin/lesson_12/lesson12_task4.kt
> +    var dayTemperature = _dayTemperature
Давай учтем все замечания из предыдущих ПРов

2024-07-05 04:59 UTC, lastbaks commented on src/main/kotlin/lesson_12/lesson12_task4.kt
> +    var dayTemperature = _dayTemperature
Ок, сделано)

2024-07-06 07:27 UTC, ievetrovdev approved these changes

2024-07-06 10:56 UTC, merged