KS-12-5 - Данные о погоде на 30 дней
lastbaks/KotlinSprintStart pull request #59
Opened 2024-07-05 18:09 UTC by lastbaks

Готово. Мне было интересно добавить немного возможностей, поэтому я добавил в класс параметры, позволяющие при необходимости вывести информацию о погоде на каждый день с указанием месяца и дня через days.forEach.

2024-07-06 07:47 UTC, ievetrovdev requested changes

2024-07-06 07:47 UTC, ievetrovdev commented on src/main/kotlin/lesson_12/lesson12_task5.kt
> +        fun createDays(count: Int, month: String): List<WeatherDataVersion5> {
Давай не будем делать эту функцию внутри класса WeatherDataVersion5, так как этот класс должен отвечать только за хранение информации об осадках.

2024-07-06 07:47 UTC, ievetrovdev commented on src/main/kotlin/lesson_12/lesson12_task5.kt
> +    val dayTemperatures = mutableListOf<Int>()
Можно убрать эти лишние списки, если использовать функцию map для получения температур и filter для получения осадков

2024-07-06 20:08 UTC, lastbaks commented on src/main/kotlin/lesson_12/lesson12_task5.kt
> +        fun createDays(count: Int, month: String): List<WeatherDataVersion5> {
Ок, вынес эту функцию из класса.

2024-07-06 20:16 UTC, lastbaks commented on src/main/kotlin/lesson_12/lesson12_task5.kt
> +    val dayTemperatures = mutableListOf<Int>()
Хорошо. Убрал отдельные списки,  сделал получение данных о температуре через map, а для получения осадков, а для получения осадков тогда предлагаю еще упростить код:
через filter получается так: listOfWeatherData.filter { it.isRainy }.count()
а можно сразу через count вот так: listOfWeatherData.count { it.isRainy }

P.S. - отдельные списки были сделаны согласно Т.З. в задаче, где это отдельно прописывалось, так то логично, что они здесь лишние.

2024-07-07 06:16 UTC, ievetrovdev approved these changes

2024-07-07 20:09 UTC, merged