KS-13-3 - Телефонный справочник с пятью объектами
lastbaks/KotlinSprintStart pull request #62
Opened 2024-07-06 21:37 UTC by lastbaks

2024-07-06 21:38 UTC, ievetrovdev requested changes

2024-07-06 21:38 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson13_task3.kt
> +    }
Если компания будут одинаковая у двух контактов, то она отобразится дважды. Нужно убрать дубли в выводе

2024-07-06 22:45 UTC, lastbaks commented on src/main/kotlin/lesson_13/lesson13_task3.kt
> +    }
Вот тут у меня вопрос, который я возможно не смог решить. Первым делом я попробовал использовать метод distinct у списка  contactList. Одинаковые названия компаний остались. Поискал в сети, нашел информацию о множестве Set -  преобразовал список в Set, но все равно одинаковые называния остались. Попробовал сделать новый пробный список String, и переделать его в Set - в пробном все получилось. Тогда я подумал, что проблема в том, что у нас список объектов, а не примитивов, и метод distinct удалил бы объект только в том случае, если у нас два объекта одинаковы, а у нас одинаковое лишь одно из полей объекта. Попробовал создать список, в который добавлять только строковые значения поля company - и на основании него сделать set. Не получилось.
И итоге получилось через второй список и уже оттуда вот таким образом:
companyNames.distinct().forEach { println(it) }

Возможно есть более простой вариант, и вот в этом у меня вопрос - можно ли сделать более просто? я не нашел

2024-07-07 23:37 UTC, ievetrovdev requested changes

2024-07-07 23:37 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson13_task3.kt
> +    companyNames.distinct().forEach { println(it) }
Есть вариант лучше, через map

contactList
    .map { it.company }

 Мапим, фильтруем на нулл, берем уникальные и выводим (можно циклом). все это можно прям провернуть подряд вызывая методы от map, получится красиво, погугли как и попробуй сделать

2024-07-07 23:37 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson13_task3.kt
> +        company = "null",
Учитывай что это не null, а именно такое название компании будет

2024-07-07 23:37 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson13_task3.kt
> +    }
Ответил ниже

2024-07-08 05:32 UTC, lastbaks commented on src/main/kotlin/lesson_13/lesson13_task3.kt
> +        company = "null",
Да, эту вложенную в задачу шутку я сразу понял. В Т.З. так и сказано - одну из компаний назвать null.

2024-07-08 05:34 UTC, lastbaks commented on src/main/kotlin/lesson_13/lesson13_task3.kt
> +    companyNames.distinct().forEach { println(it) }
Да, нашел. Спасибо за подсказку. Idea еще подсказала, что у map есть вариент mapNotNull, которая null пропускает, и при ее использовании вообще красиво получается)!

2024-07-08 20:52 UTC, ievetrovdev approved these changes
Все верно! Молодец!

2024-07-08 20:55 UTC, merged