KS-13-4 - Телефонный справочник с добавлением объекта
lastbaks/KotlinSprintStart pull request #63
Opened 2024-07-08 04:55 UTC by lastbaks

2024-07-08 20:51 UTC, ievetrovdev requested changes

2024-07-08 20:51 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson13_task4.kt
> +    }
Нет требования выводить данные  в init, сделай для этого нормальный отдельный метод, или переопредели toString

2024-07-09 04:55 UTC, lastbaks commented on src/main/kotlin/lesson_13/lesson13_task4.kt
> +    }
Готово. Перевел в простой метод.

2024-07-09 07:05 UTC, ievetrovdev requested changes

2024-07-09 07:05 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson13_task4.kt
> +        if (company == "") {
А если будет null, нужно тоже учесть такой случай

2024-07-09 10:07 UTC, lastbaks commented on src/main/kotlin/lesson_13/lesson13_task4.kt
> +        if (company == "") {
Этот пункт как раз учитывался в строке 11 -проверка на null через элвис оператор. Но можно и по другому - переписал строку 12, добавил туда вторым условием проверку на null и все обернул в "Или" - и тогда 11 строку можно закомментить. Готово.

2024-07-09 20:14 UTC, ievetrovdev requested changes

2024-07-09 20:14 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson13_task4.kt
> +//        println("Компания: ${company ?: "не указано"}")
Комментарии тут не нужны

2024-07-10 03:56 UTC, lastbaks commented on src/main/kotlin/lesson_13/lesson13_task4.kt
> +//        println("Компания: ${company ?: "не указано"}")
Ок, убрал комментарий

2024-07-10 20:33 UTC, ievetrovdev approved these changes
Отличная работа, молодец!

2024-07-10 20:34 UTC, merged