KS-13-5 - Телефонный справочник. отлов исключения
lastbaks/KotlinSprintStart pull request #64
Opened 2024-07-08 10:52 UTC by lastbaks

2024-07-08 20:53 UTC, ievetrovdev requested changes

2024-07-08 20:53 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson13_task5.kt
> +        println(e)
Почти верно, нужно вывести наименование класса ошибки, специальным методом

2024-07-09 11:04 UTC, lastbaks commented on src/main/kotlin/lesson_13/lesson13_task5.kt
> +        println(e)
Готово.

2024-07-09 20:15 UTC, ievetrovdev approved these changes
Все верно!

2024-07-10 03:53 UTC, merged