KS-14-3 - фигуры (круги и прямоугольники)
lastbaks/KotlinSprintStart pull request #67
Opened 2024-07-10 04:58 UTC by lastbaks

2024-07-10 05:27 UTC, ievetrovdev requested changes

2024-07-10 05:27 UTC, ievetrovdev commented on src/main/kotlin/lesson_14/lesson14_task3.kt
> +        return 3.14f * (radius * radius)
Эта переменная есть [в стандартной библиотеке](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.math/-p-i.html). Предлагаю импортнуть ее, чтобы не создавать свою переменную)

2024-07-10 05:27 UTC, ievetrovdev commented on src/main/kotlin/lesson_14/lesson14_task3.kt
> +        return (3.14f * 2 * radius)
Здесь также

2024-07-10 05:27 UTC, ievetrovdev commented on src/main/kotlin/lesson_14/lesson14_task3.kt
> +    open var color: String = "Черный"
Значение цветов предлагаю вынести в константы и переиспользовать

2024-07-10 05:27 UTC, ievetrovdev commented on src/main/kotlin/lesson_14/lesson14_task3.kt
> +    val circle1 = Circle("Черный", 20.0f)
Также стоит использовать константы для цветов

2024-07-10 05:27 UTC, ievetrovdev commented on src/main/kotlin/lesson_14/lesson14_task3.kt
> +        if (it.color == "Черный") {
Здесь логичнее будет смотреться when, а не if)

2024-07-10 16:20 UTC, lastbaks commented on src/main/kotlin/lesson_14/lesson14_task3.kt
> +        if (it.color == "Черный") {
Если количество цветов будет множиться - то да, так будет проще.

2024-07-11 06:59 UTC, ievetrovdev approved these changes

2024-07-11 08:45 UTC, merged