KS-11-5 - создание классов форума с текстовыми сообщениями
lastbaks/KotlinSprintStart pull request #69
Opened 2024-07-11 20:15 UTC by lastbaks

2024-07-12 05:35 UTC, ievetrovdev requested changes

2024-07-12 05:35 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task5.kt
> +    kotlinLearningForum.addMember("Константин Леман")
При создании пользователя возможно стоит его возвращать, чтобы в дальнейшем использовать его айди при создании сообщения. Сейчас непонятно откуда берется айди 0 и 1 для отправки сообщения. Можно вообще в `ForumMessage` добавить в качестве автора сообщения `ForumMember`, тогда будет однозначно понятно кто отправляет)

2024-07-13 14:24 UTC, lastbaks commented on src/main/kotlin/lesson_11/lesson11_task5.kt
> +    kotlinLearningForum.addMember("Константин Леман")
Вначале я не совсем понял, что значит "возвращать" пользователя, т.к. функция у меня и так возвращает значение, попросил сына помочь разобраться - он мне показал мои ошибки, стало понятнее, заодно в плане "разбора полетов" сделали с ним возможную ситуацию, при которой обращение к отсутствующему автору.

2024-07-14 06:41 UTC, ievetrovdev approved these changes

2024-07-14 06:42 UTC, merged