KS-15-1 - классы летающих и плавающих существ
lastbaks/KotlinSprintStart pull request #70
Opened 2024-07-12 04:36 UTC by lastbaks

2024-07-12 22:47 UTC, ievetrovdev requested changes

2024-07-12 22:47 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/lesson15_task1.kt
> +class Duck() : Bird() {
Утка тоже умеет плавать, попробуй использовать множественное наследование

2024-07-12 22:47 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/lesson15_task1.kt
> +abstract class Bird : FLying {
Использование абстрактных классов может быть хорошей идеей во многих случаях, но тут выглядит так что технически много птиц умеет летать и плавать, и в целом есть такие рыбы что могут летать (или прыгать из воды). В общем выглядит что это может быть лучше отказать от этого, и работать уже сразу а конкретными классами животных и интерфейсами для них

2024-07-13 19:01 UTC, lastbaks commented on src/main/kotlin/lesson_15/lesson15_task1.kt
> +class Duck() : Bird() {
Ну да, действительно. Я реально не воспринял их как плавающих). Добавил.

2024-07-13 22:04 UTC, ievetrovdev requested changes

2024-07-13 22:04 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/lesson15_task1.kt
> +abstract class Fish :  Swimming {
Лишний пробел

2024-07-13 22:04 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/lesson15_task1.kt
> +class  Carp : Fish() {
Лишний пробел

2024-07-13 22:04 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/lesson15_task1.kt
> +abstract class Bird : FLying, Swimming {
Получается абсолютно любая птица плавает?

2024-07-14 05:03 UTC, lastbaks commented on src/main/kotlin/lesson_15/lesson15_task1.kt
> +abstract class Bird : FLying {
В целом данный урок является сам по себе абстракцией для проверки работы абстрактных классов. Тогда пойдем от реальности, и вообще вынесем в классы птиц и рыб только то, что в действительности их определяет. Использование данных свойств выходит за рамки урока, но если их не вынести, то можно просто сделать класс Animal и на основании его три класса - Утка, чайка и карп, но это уже выглядит совсем примитивным.

2024-07-15 04:41 UTC, lastbaks commented on src/main/kotlin/lesson_15/lesson15_task1.kt
> +abstract class Bird : FLying {
Тогда предлагаю вообще уйти от абстрактных классов, т.к., Можно конечно сделать класс Птица, и Рыба, и придумать чем они отличаются - добавить одному Клюв, перья и две ноги, другому жабры, так мы можем зайти очень далеко. Для реализации данной задачи будет достаточно не использовать наследование, а сделать три простых класса и распределить им подходящие интерфейсы (для плавания и для полета)

2024-07-15 12:34 UTC, ievetrovdev requested changes

2024-07-15 12:34 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/lesson15_task1.kt
> +
Зачем столько пустых строк, достаточно всего лишь 1й

2024-07-15 13:04 UTC, lastbaks commented on src/main/kotlin/lesson_15/lesson15_task1.kt
> +
Поправил. в IDEA в тех местах, где комментарии - эти строки незаметным образом образуются при удалении кода. Надо тренироваться в их отлове.

2024-07-15 17:31 UTC, ievetrovdev approved these changes
Все верно, молодец!

2024-07-15 17:35 UTC, merged