KS-15-3 - классы пользователей и админов форума
lastbaks/KotlinSprintStart pull request #71
Opened 2024-07-13 21:58 UTC by lastbaks

2024-07-13 22:13 UTC, ievetrovdev requested changes

2024-07-13 22:13 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/lesson15_task3.kt
> +interface AdminRoots {
Использование интерфейса тут плохая идея. Интерфейс это верхушка иерархии наследования, и должна описывать прям базовые, общие вещи. Права админа, это все таки уже конкретные методы, для работы с конкретными классами пользователей. Перенеси эти методы в класс админа, либо придумай иное решение более подходящее на твой взгляд.

2024-07-15 13:58 UTC, lastbaks commented on src/main/kotlin/lesson_15/lesson15_task3.kt
> +interface AdminRoots {
Мне кажется вполне логичным оставить методы deleteMessage и deleteUser перенести в класс админа.

2024-07-15 17:33 UTC, ievetrovdev approved these changes
Верное решение, молодец!

2024-07-15 17:36 UTC, merged