Ks 15 5 abstract classes and interfaces
lastbaks/KotlinSprintStart pull request #74
Opened 2024-07-17 19:36 UTC by lastbaks

Пользуясь случаем хочу сказать спасибо! - Задачка просто класс. Я конечно провозился с ней два вечера, но во первых сразу по некоторым моментам мозги немного "встали на место", и не будь ограничений по времени - можно было бы еще с ней позаниматься. Я добавил отдельный класс Терминал, используя его как место, куда прибывают грузы и пассажиры, и там происходит регистрация итогового количества перевозок, и тут уже можно было бы сделать несколько терминалов и устроить серию междугородних перевозок, и сделать, чтобы пассажиры и грузы нужно было искать и ехать за ними... в общем весьма позитивная задачка, спасибо!.  Жду комментариев по ошибкам.

P.S. код выложен дважды, т.к. в первый раз я случайно не поменял название и там фигурирует музыкальный магазин.

2024-07-17 22:13 UTC, ievetrovdev requested changes

2024-07-17 22:13 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/lesson15_task5.kt
> +    }
Методы startEngine и stopEngine не проверяют текущее состояние двигателя перед выполнением действий, что приводит к лишним операциям и сообщениям.

2024-07-17 22:13 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/lesson15_task5.kt
> +    fun unboardingPassengers(terminal: Terminal) {
Метод предполагает передачу объекта Terminal, что не всегда может быть удобно. Также, сообщения можно упростить. Перепиши метод так, чтобы он не требовал параметров и использовал свои свойства и переданный объект терминала.

2024-07-17 22:13 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/lesson15_task5.kt
> +    fun loadCargo(carType: String, carName: String) {
Нужен параметр для указания веса груза

2024-07-18 03:53 UTC, lastbaks commented on src/main/kotlin/lesson_15/lesson15_task5.kt
> +    }
Ок, поправил.

2024-07-18 03:58 UTC, lastbaks commented on src/main/kotlin/lesson_15/lesson15_task5.kt
> +    fun loadCargo(carType: String, carName: String) {
Ок, сделаю так. У меня была реализована концепция, где автомобили загружаются заранее подготовленными партиями груза по 250кг.

2024-07-18 04:39 UTC, lastbaks commented on src/main/kotlin/lesson_15/lesson15_task5.kt
> +    fun unboardingPassengers(terminal: Terminal) {
В моем случае я подразумевал, что терминалов может быть несколько. Немного изменил код - теперь их для примера два. Так мы можем дальше при необходимости развивать приложение, т.к. всегда возить пассажиров и грузы в одно и то же место нелогично. Причем изначально у меня как раз в параметрах не требовалось передавать метод. Функция unboardingPassengeers возвращала количество пассажиров (terminal.countArrivedPassengers += taxi.unboardingPassengers) но мне это как раз показалось нелогичным - так как логично, что везде инициатором должен быть Такси, а не Терминал. '. А вот как передать объект терминала в функцию, не через параметр, или без использования возвращаемого значения - я не нашел такого решения.

2024-07-18 21:31 UTC, ievetrovdev approved these changes
В целом все верно, хорошее решение!

2024-07-19 03:40 UTC, merged