Ks 16 5 Класс игрока с методами получения урона и лечения
lastbaks/KotlinSprintStart pull request #79
Opened 2024-07-20 17:54 UTC by lastbaks

2024-07-21 10:20 UTC, ievetrovdev requested changes

2024-07-21 10:20 UTC, ievetrovdev commented on src/main/kotlin/lesson_16/lesson16_task5.kt
> +    class Player(
Все отлично, только давай сделаем автоформатирование)

2024-07-21 10:38 UTC, lastbaks commented on src/main/kotlin/lesson_16/lesson16_task5.kt
> +    class Player(
Не вопрос. Автоформатирование применено.

2024-07-22 05:32 UTC, ievetrovdev approved these changes

2024-07-22 05:54 UTC, merged