KS-2-3 Calculating train's arrival time
lastbaks/KotlinSprintStart pull request #8
Opened 2024-06-13 04:58 UTC by lastbaks

2024-06-13 12:45 UTC, ievetrovdev requested changes

2024-06-13 12:45 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task3.kt
> +    val travelHours = travelTime / 60
Все окей, но чтобы снизить риск ошибок, предлагаю еще вынести 60 в константу. Кроме того это [магическое число](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что тоже не является хорошей практикой.

2024-06-13 12:45 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task3.kt
> +    val travelMinutes = travelTime % 60
можно чуть упростить сначала 9 39 перевести в минут, добавить 457 и из этой суммы считать итоговое время

2024-06-13 18:50 UTC, lastbaks commented on src/main/kotlin/lesson_2/lesson2_task3.kt
> +    val travelHours = travelTime / 60
Хорошо, только я еще добавлю 24 (кол-во часов в день) в константы. Оно тоже помогает сделать вычисление проще.

2024-06-13 18:50 UTC, lastbaks commented on src/main/kotlin/lesson_2/lesson2_task3.kt
> +    val travelMinutes = travelTime % 60
Готово.

2024-06-14 07:28 UTC, ievetrovdev approved these changes
с 24 все правильно, я просто приводил пример числа для константы

2024-06-14 07:31 UTC, merged