KS-17-5-Класс User без первичной инициализации
lastbaks/KotlinSprintStart pull request #85
Opened 2024-07-21 21:07 UTC by lastbaks

Класс User без первичной инициализации, с полями содержащими имя пользователя и пароль.
Пароль изменить нельзя, пароль отображается в виде звездочек.

2024-07-22 07:43 UTC, ievetrovdev requested changes

2024-07-22 07:43 UTC, ievetrovdev commented on src/main/kotlin/lesson_17/lesson17_task5.kt
> +    var userLogin: String = userLogin
при изменении логина в консоли должно печататься сообщение об успешной смене логина.
Забыл сделать

2024-07-22 07:43 UTC, ievetrovdev commented on src/main/kotlin/lesson_17/lesson17_task5.kt
> +        get() = getPassword(field)
Можно воспользоваться методом формирования строки из переданных данных, под капотом которого работает цикл. И применив его к строке возвращать нужное количество звездочек "*".repeat(field.length)

2024-07-22 15:43 UTC, lastbaks commented on src/main/kotlin/lesson_17/lesson17_task5.kt
> +        get() = getPassword(field)
Да, я про него не знал. Переделал в таком виде.

2024-07-23 07:01 UTC, ievetrovdev approved these changes

2024-07-23 09:41 UTC, merged