KS-19-4-класс танка с видами зарядов
lastbaks/KotlinSprintStart pull request #94
Opened 2024-07-26 05:12 UTC by lastbaks

2024-07-26 23:27 UTC, ievetrovdev requested changes

2024-07-26 23:27 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson19_task4.kt
> +    NO_BULLETS(0, "заряд отсутствует"),
Давай сделаем null как значение "заряд отсутствует", это будет более верной реализацией

2024-07-26 23:27 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson19_task4.kt
> +    var typeAmmo: Ammo
Давай сделаем так, что при создании танк не обязательно заряжать, пусть там будет null

2024-07-27 05:38 UTC, lastbaks commented on src/main/kotlin/lesson_19/lesson19_task4.kt
> +    NO_BULLETS(0, "заряд отсутствует"),
Согласен, переделал)

2024-07-27 05:39 UTC, lastbaks commented on src/main/kotlin/lesson_19/lesson19_task4.kt
> +    var typeAmmo: Ammo
Поправил.

2024-07-27 18:19 UTC, ievetrovdev requested changes

2024-07-27 18:19 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson19_task4.kt
> +    NO_BULLETS(null, "заряд отсутствует"),
Так как  Ammo? = null то нет смысла в этом кейсе, теперь логика твоей программы уже учитывает что null это не заряженный вариант.  NO_BULLETS(null, "заряд отсутствует") - это тоже самое, можно убрать это

2024-07-27 20:33 UTC, lastbaks commented on src/main/kotlin/lesson_19/lesson19_task4.kt
> +    NO_BULLETS(null, "заряд отсутствует"),
Я вкладывал в это такой смысл, что танк можно "разрядить" присвоив ему элемент NO_BULLETS. Если просто убрать данный элемент, то получается, что танк невозможно разрядить. Тогда предлагаю сделать так: 1. добавляю функцию removeAmmo, которая будет присваивать null типу зарядка, это будет разрядка танка. И для поддержания единообразия в названии меняю имя функции changeAmmo на insertAmmo.

2024-07-27 21:17 UTC, ievetrovdev requested changes

2024-07-27 21:17 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson19_task4.kt
> +//    NO_BULLETS(null, "заряд отсутствует"),
Нет, нужно удалять лишний код, такие комментарии допустимы только на этапе разработки, но не в пулл реквестах

2024-07-27 21:18 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson19_task4.kt
> +    NO_BULLETS(null, "заряд отсутствует"),
Отличный подход!

2024-07-28 19:09 UTC, ievetrovdev approved these changes
Все  верно!

2024-07-28 19:51 UTC, merged